// Timezone list mirrored 1:1 from replyagent (gateway-frontend/src/assets/js/timezones.json).
// Ordered by UTC offset, IANA ids. Used by workspace Manage settings (and reusable elsewhere).
// NOTE: replyagent's JSON has a duplicate "Asia/Singapore" entry — deduped here so SelectItem values stay unique.

export interface Timezone {
  id: string;   // IANA identifier, e.g. "America/Los_Angeles" — this is what gets saved
  name: string; // human label, e.g. "Pacific Time (US and Canada)"
  utc: string;  // offset, e.g. "-08:00"
}

export const TIMEZONES: Timezone[] = [
  { id: "Etc/GMT+12", name: "International Date Line West", utc: "-12:00" },
  { id: "Etc/GMT+11", name: "Coordinated Universal Time-11", utc: "-11:00" },
  { id: "Pacific/Honolulu", name: "Hawaii", utc: "-10:00" },
  { id: "America/Anchorage", name: "Alaska", utc: "-09:00" },
  { id: "America/Santa_Isabel", name: "Baja California", utc: "-08:00" },
  { id: "America/Los_Angeles", name: "Pacific Time (US and Canada)", utc: "-08:00" },
  { id: "America/Chihuahua", name: "Chihuahua, La Paz", utc: "-07:00" },
  { id: "America/Mazatlan", name: "Mazatlan", utc: "-07:00" },
  { id: "America/Phoenix", name: "Arizona", utc: "-07:00" },
  { id: "America/Denver", name: "Mountain Time (US and Canada)", utc: "-07:00" },
  { id: "America/Guatemala", name: "Central America", utc: "-06:00" },
  { id: "America/Chicago", name: "Central Time (US and Canada)", utc: "-06:00" },
  { id: "America/Regina", name: "Saskatchewan", utc: "-06:00" },
  { id: "America/Mexico_City", name: "Guadalajara, Mexico City", utc: "-06:00" },
  { id: "America/Monterrey", name: "Monterey", utc: "-06:00" },
  { id: "America/Bogota", name: "Bogota, Quito", utc: "-05:00" },
  { id: "America/Lima", name: "Lima", utc: "-05:00" },
  { id: "America/Indiana/Indianapolis", name: "Indiana (East)", utc: "-05:00" },
  { id: "America/New_York", name: "Eastern Time (US and Canada)", utc: "-05:00" },
  { id: "America/Caracas", name: "Caracas", utc: "-04:30" },
  { id: "America/Halifax", name: "Atlantic Time (Canada)", utc: "-04:00" },
  { id: "America/Asuncion", name: "Asuncion", utc: "-04:00" },
  { id: "America/La_Paz", name: "Georgetown, La Paz", utc: "-04:00" },
  { id: "America/Manaus", name: "Manaus", utc: "-04:00" },
  { id: "America/Argentina/San_Juan", name: "San Juan", utc: "-04:00" },
  { id: "America/Cuiaba", name: "Cuiaba", utc: "-04:00" },
  { id: "America/Santiago", name: "Santiago", utc: "-04:00" },
  { id: "America/St_Johns", name: "Newfoundland", utc: "-03:30" },
  { id: "America/Sao_Paulo", name: "Brasilia", utc: "-03:00" },
  { id: "America/Godthab", name: "Greenland", utc: "-03:00" },
  { id: "America/Cayenne", name: "Cayenne", utc: "-03:00" },
  { id: "America/Fortaleza", name: "Fortaleza", utc: "-03:00" },
  { id: "America/Argentina/Buenos_Aires", name: "Buenos Aires", utc: "-03:00" },
  { id: "America/Montevideo", name: "Montevideo", utc: "-03:00" },
  { id: "Etc/GMT+2", name: "Coordinated Universal Time-2", utc: "-02:00" },
  { id: "Atlantic/Cape_Verde", name: "Cape Verde", utc: "-01:00" },
  { id: "Atlantic/Azores", name: "Azores", utc: "-01:00" },
  { id: "Africa/Casablanca", name: "Casablanca", utc: "+00:00" },
  { id: "Atlantic/Reykjavik", name: "Monrovia, Reykjavik", utc: "+00:00" },
  { id: "UTC", name: "UTC", utc: "+00:00" },
  { id: "Europe/Dublin", name: "Dublin", utc: "+00:00" },
  { id: "Europe/Lisbon", name: "Lisbon", utc: "+00:00" },
  { id: "Europe/London", name: "Edinburgh, London", utc: "+00:00" },
  { id: "Etc/GMT", name: "Coordinated Universal Time", utc: "+00:00" },
  { id: "Europe/Amsterdam", name: "Amsterdam", utc: "+01:00" },
  { id: "Europe/Berlin", name: "Berlin, Bern", utc: "+01:00" },
  { id: "Europe/Rome", name: "Rome", utc: "+01:00" },
  { id: "Europe/Stockholm", name: "Stockholm", utc: "+01:00" },
  { id: "Europe/Vienna", name: "Vienna", utc: "+01:00" },
  { id: "Europe/Brussels", name: "Brussels", utc: "+01:00" },
  { id: "Europe/Copenhagen", name: "Copenhagen", utc: "+01:00" },
  { id: "Europe/Madrid", name: "Madrid", utc: "+01:00" },
  { id: "Europe/Paris", name: "Paris", utc: "+01:00" },
  { id: "Africa/Lagos", name: "West Central Africa", utc: "+01:00" },
  { id: "Europe/Belgrade", name: "Belgrade", utc: "+01:00" },
  { id: "Europe/Bratislava", name: "Bratislava", utc: "+01:00" },
  { id: "Europe/Budapest", name: "Budapest", utc: "+01:00" },
  { id: "Europe/Ljubljana", name: "Ljubljana", utc: "+01:00" },
  { id: "Europe/Prague", name: "Prague", utc: "+01:00" },
  { id: "Europe/Sarajevo", name: "Sarajevo", utc: "+01:00" },
  { id: "Europe/Skopje", name: "Skopje", utc: "+01:00" },
  { id: "Europe/Warsaw", name: "Warsaw", utc: "+01:00" },
  { id: "Europe/Zagreb", name: "Zagreb", utc: "+01:00" },
  { id: "Africa/Windhoek", name: "Windhoek", utc: "+01:00" },
  { id: "Europe/Athens", name: "Athens", utc: "+02:00" },
  { id: "Europe/Bucharest", name: "Bucharest", utc: "+02:00" },
  { id: "Europe/Istanbul", name: "Istanbul", utc: "+02:00" },
  { id: "Europe/Helsinki", name: "Helsinki", utc: "+02:00" },
  { id: "Europe/Kiev", name: "Kiev", utc: "+02:00" },
  { id: "Europe/Riga", name: "Riga", utc: "+02:00" },
  { id: "Europe/Sofia", name: "Sofia", utc: "+02:00" },
  { id: "Europe/Tallinn", name: "Tallinn", utc: "+02:00" },
  { id: "Europe/Vilnius", name: "Vilnius", utc: "+02:00" },
  { id: "Africa/Cairo", name: "Cairo", utc: "+02:00" },
  { id: "Asia/Damascus", name: "Damascus", utc: "+02:00" },
  { id: "Asia/Amman", name: "Amman", utc: "+02:00" },
  { id: "Africa/Johannesburg", name: "Harare, Pretoria", utc: "+02:00" },
  { id: "Asia/Jerusalem", name: "Jerusalem", utc: "+02:00" },
  { id: "Asia/Beirut", name: "Beirut", utc: "+02:00" },
  { id: "Asia/Baghdad", name: "Baghdad", utc: "+03:00" },
  { id: "Europe/Minsk", name: "Minsk", utc: "+03:00" },
  { id: "Asia/Kuwait", name: "Kuwait", utc: "+03:00" },
  { id: "Asia/Riyadh", name: "Riyadh", utc: "+03:00" },
  { id: "Africa/Nairobi", name: "Nairobi", utc: "+03:00" },
  { id: "Asia/Tehran", name: "Tehran", utc: "+03:00" },
  { id: "Europe/Moscow", name: "Moscow, St. Petersburg, Volgograd", utc: "+04:00" },
  { id: "Europe/Volgograd", name: "Volgograd", utc: "+04:00" },
  { id: "Asia/Tbilisi", name: "Tbilisi", utc: "+04:00" },
  { id: "Asia/Yerevan", name: "Yerevan", utc: "+04:00" },
  { id: "Asia/Dubai", name: "Abu Dhabi, Muscat", utc: "+04:00" },
  { id: "Asia/Baku", name: "Baku", utc: "+04:00" },
  { id: "Indian/Mauritius", name: "Port Louis", utc: "+04:00" },
  { id: "Asia/Kabul", name: "Kabul", utc: "+04:30" },
  { id: "Asia/Tashkent", name: "Tashkent", utc: "+05:00" },
  { id: "Asia/Karachi", name: "Islamabad, Karachi", utc: "+05:00" },
  { id: "Asia/Colombo", name: "Sri Jayewardenepura Kotte", utc: "+05:30" },
  { id: "Asia/Kolkata", name: "Chennai, Kolkata, Mumbai, New Delhi", utc: "+05:30" },
  { id: "Asia/Kathmandu", name: "Kathmandu", utc: "+05:45" },
  { id: "Asia/Almaty", name: "Astana", utc: "+06:00" },
  { id: "Asia/Dhaka", name: "Dhaka", utc: "+06:00" },
  { id: "Asia/Yekaterinburg", name: "Yekaterinburg", utc: "+06:00" },
  { id: "Asia/Yangon", name: "Yangon", utc: "+06:30" },
  { id: "Asia/Bangkok", name: "Bangkok, Hanoi", utc: "+07:00" },
  { id: "Asia/Jakarta", name: "Jakarta", utc: "+07:00" },
  { id: "Asia/Novosibirsk", name: "Novosibirsk", utc: "+07:00" },
  { id: "Asia/Krasnoyarsk", name: "Krasnoyarsk", utc: "+08:00" },
  { id: "Asia/Ulaanbaatar", name: "Ulaanbaatar", utc: "+08:00" },
  { id: "Asia/Shanghai", name: "Beijing, Chongqing", utc: "+08:00" },
  { id: "Asia/Hong_Kong", name: "Hong Kong, Urumqi", utc: "+08:00" },
  { id: "Asia/Urumqi", name: "Urumqi", utc: "+08:00" },
  { id: "Australia/Perth", name: "Perth", utc: "+08:00" },
  { id: "Asia/Singapore", name: "Kuala Lumpur, Singapore", utc: "+08:00" },
  { id: "Asia/Taipei", name: "Taipei", utc: "+08:00" },
  { id: "Asia/Irkutsk", name: "Irkutsk", utc: "+09:00" },
  { id: "Asia/Seoul", name: "Seoul", utc: "+09:00" },
  { id: "Asia/Tokyo", name: "Osaka, Sapporo, Tokyo", utc: "+09:00" },
  { id: "Australia/Darwin", name: "Darwin", utc: "+09:30" },
  { id: "Australia/Adelaide", name: "Adelaide", utc: "+09:30" },
  { id: "Australia/Hobart", name: "Hobart", utc: "+10:00" },
  { id: "Asia/Yakutsk", name: "Yakutsk", utc: "+10:00" },
  { id: "Australia/Brisbane", name: "Brisbane", utc: "+10:00" },
  { id: "Pacific/Port_Moresby", name: "Guam, Port Moresby", utc: "+10:00" },
  { id: "Australia/Sydney", name: "Canberra, Melbourne, Sydney", utc: "+10:00" },
  { id: "Asia/Vladivostok", name: "Vladivostok", utc: "+11:00" },
  { id: "Pacific/Guadalcanal", name: "Solomon Islands, New Caledonia", utc: "+11:00" },
  { id: "Etc/GMT-12", name: "Coordinated Universal Time+12", utc: "+12:00" },
  { id: "Pacific/Fiji", name: "Fiji, Marshall Islands", utc: "+12:00" },
  { id: "Asia/Magadan", name: "Magadan", utc: "+12:00" },
  { id: "Pacific/Auckland", name: "Auckland, Wellington", utc: "+12:00" },
  { id: "Pacific/Tongatapu", name: "Nuku'alofa", utc: "+13:00" },
  { id: "Pacific/Apia", name: "Samoa", utc: "+13:00" },
];
