name: Deploy to Firebase Hosting on merge
on:
  push:
    branches:
      - main
      - side-bar
      - update1
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install server dependencies
        run: cd server && npm ci
      - run: npm ci && npm run build
      
      # Deploy Main Branch to comm-platform-5fdce
      - if: github.ref == 'refs/heads/main'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COMM_PLATFORM_5FDCE }}
          channelId: live
          projectId: comm-platform-5fdce

      # Deploy Side-Bar Branch to product-one-4d742
      - if: github.ref == 'refs/heads/side-bar'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_PRODUCT_ONE_4D742 }}
          channelId: live
          projectId: product-one-4d742

      # Deploy Update1 Branch to update-one-5fdce (site in comm-platform-5fdce)
      - if: github.ref == 'refs/heads/update1'
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: ${{ secrets.GITHUB_TOKEN }}
          firebaseServiceAccount: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_COMM_PLATFORM_5FDCE }}
          channelId: live
          projectId: comm-platform-5fdce
          target: update-site
